# Congo theme parameters
colorScheme = "ocean"
defaultAppearance = "light"
autoSwitchAppearance = true

enableSearch = false
enableCodeCopy = true

[header]
  layout = "basic"

[footer]
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile"
  showRecent = false
  recentLimit = 5

[article]
  showDate = true
  showDateUpdated = false
  showAuthor = true
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = false
